# Generated by Django 5.1.1 on 2024-09-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_blogs_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='saved_post',
            field=models.ManyToManyField(related_name='saved_post', to='myapp.blogs'),
        ),
    ]
