# Generated by Django 5.1.1 on 2024-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userinfo_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='about_yourself',
            field=models.TextField(default='Not Updated Yet...', max_length=100),
        ),
    ]
